### ISSUE TITLE
tear down cluster

### ISSUE THREAD

**Issue by ygodonou** [confluentinc/operator-earlyaccess#15]
Please update the tear down section in the secure-authn-encrypt-deploy and cp-rbac-deploy  to include the full path:

- secure-authn-encrypt-deploy
`kubectl delete -f $TUTORIAL_HOME/secure-producer-app-data.yaml `
`kubectl delete -f $TUTORIAL_HOME/confluent-platform-secure.yaml`

- cp-rbac-deploy
`kubectl delete -f $TUTORIAL_HOME/confluent-platform-rbac-secure.yaml`

**Comment by arodoni** [comment]
Resolved
