### ISSUE TITLE
Networking Labs Should Have Both Internal and External Clients in the Validation Section

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/operator-earlyaccess#41]
The networking labs currently just run a producer inside the k8s cluster for validation, but these labs are supposed to show how external clients can access confluent resources. I suggest adding a kafka-console-consumer command from outside the k8s cluster to show data being produced internally and consumed externally.

**Comment by chuck-confluent** [comment]
I will add that we should not only have kafka clients inside and outside k8s, but we should also show http clients reach RESTful services both inside and outside k8s. For example, make dummy curl commands to schema registry and kafka connect endpoints

**Comment by chuck-confluent** [comment]
The host based lab doesn't use control center. There is port forwarding used here: https://github.com/confluentinc/operator-earlyaccess/tree/master/external-access-static-host-based#validate-in-control-center

I'd suggest exposing control center through ingress as well, just like the loadbalancer lab.

**Comment by arodoni** [comment]
Host-based static access is only supported for Kafka. Control Center cannot be configured for that external access. @chuck-confluent
