### ISSUE TITLE
static host based routing lab -- Producer app uses "operator" namespace instead of "confluent"

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/operator-earlyaccess#48]
the producer app yaml file uses "operator" rather than "confluent" namespace.

**Comment by arodoni** [comment]
That is intentional to show that you can connect to Kafka and create a
topic in a different namespace.

**Comment by chuck-confluent** [comment]
@arodoni Thanks! It gives an error because that namespace is never created in this lab. I would suggest being consistent with the loadbalancer lab that creates a namespace called `myclient`, or perhaps even more descriptive like `separate-kafka-client-namespace` to underscore that the client is able to reach kafka from outside.

It does still bother me that this lab doesn't have a client from entirely outside the kubernetes cluster. We would need to create a truststore outside of kubernetes for this to work.

**Comment by chuck-confluent** [comment]
It looks like the producer app actually **must** be in the "confluent" namespace. Otherwise, it won't have access to the `kafka-pkcs12` secret that is created in the confluent namespace. I am not 100% sure, but I think that secret is generated by the operator when creating confluent services.

**Comment by arodoni** [comment]
The secret could be copied to the Operator namespace. Or we can just change
the topic namespace to Confluent.

**Comment by chuck-confluent** [comment]
If the changes proposed in https://github.com/confluentinc/operator-earlyaccess/pull/53 are accepted, this issue will become irrelevant
